// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddProduct(arg1:string,arg2:string):Promise<void>;

export function DeleteProduct(arg1:number):Promise<void>;

export function DeleteProducts(arg1:Array<number>):Promise<void>;

export function GetProducts():Promise<Array<models.Product>>;

export function SearchProducts(arg1:string):Promise<Array<models.Product>>;

export function UpdateProduct(arg1:number,arg2:string,arg3:string):Promise<void>;
