// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProduct(arg1, arg2) {
  return window['go']['main']['App']['AddProduct'](arg1, arg2);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function DeleteProducts(arg1) {
  return window['go']['main']['App']['DeleteProducts'](arg1);
}

export function GetProducts() {
  return window['go']['main']['App']['GetProducts']();
}

export function SearchProducts(arg1) {
  return window['go']['main']['App']['SearchProducts'](arg1);
}

export function UpdateProduct(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProduct'](arg1, arg2, arg3);
}
