name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true
      
      - name: Print Go version
        run: go version
      
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.56.2
          golangci-lint --version
      
      - name: Run golangci-lint
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          golangci-lint run --verbose | tee lint_output.txt
        continue-on-error: true
      
      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: lint_output.txt
          retention-days: 90
          if-no-files-found: warn

      - name: Summary
        run: |
          echo "Lint completed at $(date)" 
          echo "### Lint Summary" >> $GITHUB_STEP_SUMMARY
          echo "Lint completed at $(date)" >> $GITHUB_STEP_SUMMARY 