name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Print environment info
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub event: ${{ github.event_name }}"
          echo "Runner OS: ${{ runner.os }}"
          ls -la

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true
      
      - name: Print Go version
        run: go version
      
      - name: Check workspace structure
        run: |
          echo "Workspace structure:"
          find . -type f -not -path "*/\.*" | sort

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
          args: --verbose
          skip-pkg-cache: true
          skip-cache: true
          
      - name: Run standalone linter for logs
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run --verbose > lint_output.txt || true
      
      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: lint_output.txt
          retention-days: 90
          if-no-files-found: warn

      - name: Summary
        run: |
          echo "Lint completed at $(date)" 
          echo "### Lint Summary" >> $GITHUB_STEP_SUMMARY
          echo "Lint completed at $(date)" >> $GITHUB_STEP_SUMMARY 