name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Print environment info
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub event: ${{ github.event_name }}"
          echo "Runner OS: ${{ runner.os }}"
          ls -la

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true
      
      - name: Print Go version
        run: go version
      
      - name: Check workspace structure
        run: |
          echo "Workspace structure:"
          find . -type f -not -path "*/\.*" | sort

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --verbose

      - name: Summary
        run: echo "Lint completed at $(date)" 